### ISSUE TITLE
No backspace on Linux Mint

### ISSUE THREAD

**Issue by MS3FGX** [HenrySeed/TerminalToDo#1]
Some environmental differences perhaps, but on Linux Mint the backspace key comes through as KEY_BACKSPACE and doesn't get detected with the current code. Making the following change to line 175 in main.py got it working:

`elif keyNum == 127 or key == "KEY_BACKSPACE":`

**Comment by HenrySeed** [comment]
Thanks! Ill push the fix soon :)

**Comment by HenrySeed** [comment]
This has been fixed in the latest commit
